# Input file for the BEEPmbp model

########### INFERENCE DETAILS #############

# Perform a simulation.
mode      = "inf"


# The format used for representing times
timeformat = "year-month-day"

# The starting and ending times (in days or dates).
start = "2020-02-01"
end = "2020-06-15"

# The random seed used to run the simulation.
seed      = 0

# The output directory
outputdir	= "OutputMSOATest"

# The number of MCMC chains.
nchain    = 1

# The number of MCMC samples.
nsamp     = 5000

# The minimum and maximum inverse temperatures
invTmin 	= 0.25
invTmax 	= 0.25

########### THE MODEL #############

# Defines the compartments in the model.
# Format: 'inf' gives the relative infectivity, 'dist' gives the distribution for waiting time.
# Here 'exp' stands for exponential and 'lognorm' stands for lognormal follow by any parameters which define these distributions.

comps			= [{name = "S", inf=0.0},
						 {name = "E", inf=0.0},
						 {name = "A", inf=1.0},
						 {name = "R", inf=0.0},
						 {name = "P", inf=1.0},
						 {name = "I", inf=1.0},
						 {name = "C", inf=0.0},
						 {name = "H", inf=0.0},
						 {name = "D", inf=0.0}]

						 
# Defines transitions between compartments.
# Format: 'from' gives the initial compartment, 'to' gives the final compartment and 'prob' defines a branching probability.
# Note when a compartmental model has transitions to two others, only the probability down one branch needs to be defined.

trans   	=	[{from="S", to="E", dist="infection"},
						 {from="E", to="P", dist="lognorm", mean="muE", cv="cvE", prob="probEP"},
						 {from="E", to="A", dist="lognorm", mean="muE", cv="cvE"},
						 {from="A", to="R", dist="exp", mean="tA"},
						 {from="P", to="I", dist="exp", mean="tP"},
						 {from="I", to="H", dist="exp", mean="tI", prob="probIH"},
						 {from="I", to="C", dist="exp", mean="tI", prob="probIC"},
						 {from="I", to="R", dist="exp", mean="tI"},
						 {from="C", to="D", dist="lognorm", mean="muC", cv="cvC"},
						 {from="H", to="D", dist="lognorm", mean="muHD", cv="cvHD", prob="probHD"},
						 {from="H", to="R", dist="lognorm", mean="muHR", cv="cvHR"}]
						 
# Defines the parameters in the model

params		= [{name="beta0", value=1.0},        # The values for the beta spline (a step function in this case)
						 {name="beta1", value=0.9},
						 {name="beta2", value=0.8},        # The values for the beta spline (a step function in this case)
						 {name="beta3", value=0.75},
						 {name="beta4", value=0.7},
						 {name="beta5", value=0.1},
						 {name="beta6", value=0.1},
						 {name="beta7", value=0.12},
						 {name="beta8", value=0.2},
						 {name="beta9", value=0.30},
						 {name="beta10", value=0.44},
						 {name="beta11", value=0.6},
						 {name="phi", value=1.0},          # The values for the phi spline (a step function to zero)
						 {name="muE", value=4.5},                                  # The latent period
						 {name="cvE", value=0.533},	                               # The coefficent of variation for latent period			 
						 {name="tA", value=8.0},                                   # Mean time spend in asymptomatic state
						 {name="tP", value=1.5},                                   # Mean time spend in pre-symptomatic state
						 {name="tI",  value=10.0},         # Mean time spend in infectious state
					   {name="muHD", value=20.0},         # Mean time for hospital deaths
						 {name="cvHD", value=0.5},          # The coefficent of variation for hospital deaths
						 {name="muHR", value=25.0},         # Mean time for hospital recoveries
						 {name="cvHR", value=2.0},          # The coefficent of variation for hospital recoveries
						 {name="muC", value=18.0},          # Mean time spend in critical compartment
						 {name="cvC", value=0.8},           # The coefficent of variation in critical compartment
						 {name="probEP", value=0.75},                              # Probability of being symptomatic
						 {name="probIH", value=0.2},                               # Probability of hospitalised given in I state
						 {name="probIC", value=0.21},        # Probability of death in community 
						 {name="probHD", value=0.35},       # Probability of death given hospitalised 
						 {name="den_slope", value=0.2}     # The dependency of contact rate on log(population density)
						 #{name="regeff_sigma", value=0.05}   # The standard deviation in the regional effect
						 ]   
# {name="logbeta", value=-1.18}, 
						

	
priors		= [{name="beta0", type="uniform", min=0.0, max=1.0},        # The values for the beta spline (a step function in this case)
						 {name="beta1", type="uniform", min=0.0, max=1.0},
						 {name="beta2", type="uniform", min=0.0, max=1.0},
						 {name="beta3", type="uniform", min=0.0, max=1.0},
						 {name="beta4", type="uniform", min=0.0, max=1.0},
						 {name="beta5", type="uniform", min=0.0, max=1.0},
						 {name="beta6", type="uniform", min=0.0, max=1.0},
						 {name="beta7", type="uniform", min=0.0, max=1.0},
						 {name="beta8", type="uniform", min=0.0, max=1.0},
						 {name="beta9", type="uniform", min=0.0, max=1.0},
						 {name="beta10", type="uniform", min=0.0, max=1.0},
						 {name="beta11", type="uniform", min=0.0, max=1.0},
						 {name="phi", type="uniform", min=0.0, max=10.0},          # The values for the phi spline (a step function to zero)
						 {name="muE", value=4.5},                                  # The latent period
						 {name="cvE", value=0.533},	                               # The coefficent of variation for latent period			 
						 {name="tA", value=8.0},                                   # Mean time spend in asymptomatic state
						 {name="tP", value=1.5},                                   # Mean time spend in pre-symptomatic state
						 {name="tI",  value=10.0},                                 # Mean time spend in infectious state
						 {name="muHD", type="uniform", min=0.0, max=40.0},         # Mean time for hospital deaths
						 {name="cvHD", type="uniform", min=0.1, max=3.0},          # The coefficent of variation for hospital deaths
						 {name="muHR", type="uniform", min=0.0, max=40.0},         # Mean time for hospital recoveries
						 {name="cvHR", type="uniform", min=0.1, max=5.0},          # The coefficent of variation for hospital recoveries
						 {name="muC", type="uniform", min=0.0, max=40.0},          # Mean time spend in critical compartment
						 {name="cvC", type="uniform", min=0.05, max=3.0},          # The coefficent of variation in critical compartment
						 {name="probEP", value=0.75},                              # Probability of being symptomatic
						 {name="probIH", value=0.2},                               # Probability of hospitalised given in I state
						 {name="probIC", type="uniform", min=0.0, max=1.0},        # Probability of death in community 
						 {name="probHD",  type="uniform", min=0.0, max=1.0},       # Probability of death given hospitalised 
						 {name="den_slope",type="uniform", min=0.0, max=0.4}       # The dependency of contact rate on log(population density)
						 #{name="regeff_sigma",type="uniform", min=0.0, max=0.4}  
						]  
						
						#	 {name="logbeta", type="uniform", min=-3.0, max=-0.5}, 
					
					
# The maximum number of infected individuals

infmax 		= 200000

# Defines the linear spline used to represent disease transmission parameter beta.
# Format: The name of the parameter followed by the time of the spline point.

betaspline= [{param="beta0", time="start"}, 
						 {param="beta1", time="2020-02-10"},
						 {param="beta2", time="2020-02-24"},
						 {param="beta3", time="2020-03-09"}, 
						 {param="beta4", time="2020-03-23"},
						 {param="beta5", time="2020-03-23"},
						 {param="beta6", time="2020-04-06"},						 
						 {param="beta7", time="2020-04-20"}, 
						 {param="beta8", time="2020-05-04"},	
						 {param="beta9", time="2020-05-18"},							
						 {param="beta10", time="2020-06-01"},													 
						 {param="beta11", time="end"}]				

# Defines the linear spline used to represent external force of infection phi.
# Format: The name of the parameter followed by the time of the spline point. Note, The parameter 'zero' sets the value to zero.

phispline= [{param="phi", time="start"},
						{param="phi", time="2020-03-23"},
						{param="zero", time="2020-03-23"}, 
					  {param="zero", time="end"}]
						
# The age groups used in the analysis.
# Format: The age range followed by a parameter giving the relative susceptibility (on the log scale). 
# Note, one parameter is set to 'zero' and the other parameters give the susceptibity relative to that group.

ages			= [{range="all", sus="zero"}]

# Other demographic categories
# Format: The name of the category is given followed by the potential values it can take along with their relative susceptibilities.

#democats	= [[{value="Male", sus="sus_male"}, {value="Female", sus="zero"}] ]


# Covariates for area ('func' gives the fuctional transformation which can be 'linear' or 'log')

covars		= [{name="density", param="den_slope", func="log"}]


# Defines discrete time periods. This example is for before and after lockdown

timep = [{name="beforeLD", tend="2020-03-23"}, {name="afterLD", tend="end"}]


########### THE DATA #############

# The data directory

#datadir		= "examples/Data_ScotlandRegion"
datadir		= "examples/Data_ScotlandMSOA"
#datadir		= "examples/Data_example"

# A table giving data regions (e.g. "Lanarkshire	S08000032").
# Format: Tab-separated with region name then region code.

regions		= "regiondata.txt"


# A table giving information about areas.
# Format tab-separated table with: Area code, geographical position (long,lat), region code, columns for covariates (e.g. density of population), columns for populations in different age groups, columns for other deomgraphic categories (giving percentages).

areas			= "areadata.txt"


# Generates Q matrices from geographic and age mixing matrices
agemix		= {Nall="Ndata_all.txt", Nhome="Ndata_home.txt", Nother="Ndata_other.txt", Nschool="Ndata_school.txt", Nwork="Ndata_work.txt"}
geomix		= {M="Mdata.txt"}
genQoutput= {localhome="Q_local_home_data", flowall="Q_flow_all_data"}


# A list of different Q tensors which act at different periods (timep is before and after lockdown)
# and on different compartments (as defined by comp).
# The files provide information on the actual Q tensor itself.

Q					= [{ timep="beforeLD", comp="I", name="Q_local_home_data"},
						 { timep="afterLD", comp="I", name="Q_local_home_data"},
						 { timep="beforeLD", comp="P", name="Q_flow_all_data"},
						 { timep="afterLD", comp="P", name="Q_local_home_data"},
						 { timep="beforeLD", comp="A", name="Q_flow_all_data"},
						 { timep="afterLD", comp="A", name="Q_local_home_data"}]
 
 
# Sets the threshold below which the true value lies

threshold = 5 

 
# The observed numbers of transitions between different compartments.
# Format: 'from' comapartment, 'to' compartment, the area used by the data ('reg'=on a regional level, 'all'=across all regions), the name of the file, the start time and the units used.

#transdata	= [{from="I", to="H", area="reg", file="IH.txt", start="2020-03-01", units="weeks"}]

transdata	= [{from="I", to="H", area="all", file="IH.txt", start="2020-03-01", units="days"},
						 {from="H", to="D", area="all", file="HD_NRS.txt", start="2020-03-16", units="weeks"},
						 {from="C", to="D", area="all", file="ID_NRS.txt", start="2020-03-16", units="weeks"}
							]

#transdata	= [{from="I", to="H", area="reg", file="IH_sim.txt", start="2020-02-01", units="weeks"},	
#					   {from="C", to="D", area="reg", file="CD_sim.txt", start="2020-02-01", units="weeks"}]

						 
# The observed population number in different compartments
# Format: 'comp' gives the name of the compartment, the area used by the data ('reg'=on a regional level, 'all'=across all regions), the name of the file, the start time and the units used.

popdata	=[{comp="D", area="reg", file="D_NRS_reg.txt", start="2020-03-16", units="weeks"},
{comp="H", area="reg", file="H_reg.txt", start="2020-02-28", units="weeks"}]
	
						 
# Gives the percentages for marginal distributions.
						 
#margdata = 	[{from="I", to="H", area="all", type="age", file="IH_age.txt"}]
#						 {from="I", to="D", area="all", type="age", file="ID_age.txt"},
#						 {from="I", to="R", area="all", type="age", file="IR_age.txt"},
#						 {from="H", to="D", area="all", type="age", file="HD_age.txt"}]
